# Generated by Django 3.0.6 on 2020-05-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('currency', models.CharField(max_length=10)),
                ('num_market_pairs', models.IntegerField()),
                ('circulating_supply', models.DecimalField(decimal_places=6, max_digits=22)),
                ('total_supply', models.DecimalField(decimal_places=6, max_digits=22)),
                ('last_updated', models.DateField()),
                ('price', models.DecimalField(decimal_places=20, max_digits=30)),
                ('price_currency', models.CharField(max_length=10)),
                ('volume_24h', models.DecimalField(decimal_places=6, max_digits=22)),
                ('percent_change_1h', models.DecimalField(decimal_places=8, max_digits=11)),
                ('percent_change_24h', models.DecimalField(decimal_places=8, max_digits=11)),
                ('percent_change_7d', models.DecimalField(decimal_places=8, max_digits=11)),
                ('market_cap', models.DecimalField(decimal_places=6, max_digits=22)),
                ('last_price_updated', models.DateField()),
            ],
        ),
    ]
