# Generated by Django 3.0.6 on 2020-05-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='last_price_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
